export const REQUEST_ELEMENTS = 'REQUEST_ELEMENTS'
export const RECEIVE_ELEMENTS = 'RECEIVE_ELEMENTS'
export const INVALIDATE_ELEMENTS = 'INVALIDATE_ELEMENTS'

export const baseURL = "http://127.0.0.1:5000/upload";